question_data = [
{"text": "Název měny v Uzbekistánu je sum", "answer": "Ano", "correct answer": ""},
{"text": "Patagonie zasahuje do dvou států, kterými jsou Argentina a Peru", "answer": "Ne", "correct answer": "Patagonie se nachází na pomezí Argentiny a Chile"},
{"text": "Nejstarší prales v Evropě se jmenuje Bělověžský", "answer": "Ano", "correct answer": ""},
{"text": "Mezi Africkou litosférickou deskou a Somálskou litosférickou deskou je konvergentní rozhraní", "answer": "Ne", "correct answer": "Mezi nimi je divergentní rozhraní"},
{"text": "Největší jezero v Severní Americe je jezero Medvědí", "answer": "Ne", "correct answer": "Hořejší jezero"},
{"text": "40. stupeň rovnoběžky severní zeměpisné šířky tvoří převážnou hranici mezi Severní a Jižní Koreou", "answer": "Ne", "correct answer": "Hranici tvoří 38. rovnoběžka severní zeměpisné šířky"},
{"text": "Prameny řeky Amazonky objevil Němec Georg Hohermuth", "answer": "Ne", "correct answer": "Její prameny objevil český hydrolog Bohumír Jánský se svým týmem"},
{"text": "Region 'Nová Akvitánie' se nachází v Itálii", "answer": "Ne", "correct answer": "Tento region se nachází ve Francii"},
{"text": "Eritrea v minulosti byla italskou kolonií", "answer": "Ano", "correct answer": ""},
{"text": "Mys Canaveral najdeme v jižní části Kalifornského poloostrova", "answer": "Ne", "correct answer": "Nachází se na jižním cípu Floridského poloostrova"},
{"text": "Druhá nejvyšší hora světa K2 se nachází v pohoří Himálaj", "answer": "Ne", "correct answer": "Nachází se v pohoří Karákoram"},
{"text": "V Bolívii žije více než 20 milionů obyvatel", "answer": "Ne", "correct answer": "V Bolívii žije jen přibližně 12 milionů obyvatel"},
{"text": "Funkci vatikánské armády zastává švýcarská garda", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Namibie je Windhoek", "answer": "Ano", "correct answer": ""},
{"text": "Severoamerická dohoda o volném obchodu je zkráceně NAFTA", "answer": "Ano", "correct answer": ""},
{"text": "Ptakopysk žijící v Austrálii patří mezi vačnatce", "answer": "Ne", "correct answer": "Ptakopysk je zástupce ptakořitních"},
{"text": "Ohňová země se nachází u jižního cípu Jižní Ameriky", "answer": "Ano", "correct answer": ""},
{"text": "Rozloha České republiky je bezmála 79 000 km čtverečních", "answer": "Ano", "correct answer": ""},
{"text": "Kapské město je největší město v Jihoafrické republice", "answer": "Ne", "correct answer": "Kapské město je druhé největší"},
{"text": "Národní park Blue and John Crow Mountains se nachází na Jamajce", "answer": "Ano", "correct answer": ""},
{"text": "Mongolsko je největší vnitrozemský stát na světě", "answer": "Ne", "correct answer": "Mongolsko je v současnosti druhým největším vnitrozemským státem"},
{"text": "Ekvádor je pojmenován podle slova Ecuador, které španělsky znamená 'rovník'", "answer": "Ano", "correct answer": ""},
{"text": "Nejnavštěvovanější město v Polsku je Varšava", "answer": "Ne", "correct answer": "Krakov"},
{"text": "Ekvivalentní název pro Etiopii je 'Habeš'", "answer": "Ano", "correct answer": ""},
{"text": "rocker Carlos Santana je Mexičan", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší horou v Rusku je Elbrus", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní nerostnou surovinou, která tvoří velkou část HDP Trinidadu a Tobaga je ropa", "answer": "Ano", "correct answer": ""},
{"text": "Řeka Dněpr protéká Moldavskem", "answer": "Ne", "correct answer": "Dněpr Moldavskem neprotéká"},
{"text": "Název měny v Ugandě je ugandský dolar", "answer": "Ne", "correct answer": "ugandský šilink"},
{"text": "Kanadská ekonomika je desátou největší ekonomikou na světě", "answer": "Ano", "correct answer": ""},
{"text": "Celé území Nového Zélandu patří do mírného klimatického pásu", "answer": "Ne", "correct answer": "Severní část severního ostrova spadá do subtropického klimatického pásu"},
{"text": "Region Gran Chaco na západě Paraguaye pokrývají výhradně tropické deštné lesy", "answer": "Ne", "correct answer": "Jeho typickou vegetací jsou savany a polopouště"},
{"text": "Nejsevernějším bodem v Evropě je mys Nordkinn v Norsku", "answer": "Ano", "correct answer": ""},
{"text": "Pobřeží Slonoviny se stalo nezávislým státem v roce 1962", "answer": "Ne", "correct answer": "Tento stát se osamostatnil již v roce 1960"},
{"text": "Hlavním městem(správním střediskem) na Arubě je Willemstad", "answer": "Ne", "correct answer": "Oranjestad"},
{"text": "Mezi hlavní hospodářské odvětví na Srí Lance patří zpracování diamantů", "answer": "Ne", "correct answer": "Diamanty se na Srí Lance vůbec nezpracovávají"},
{"text": "Guyana je součástí Commonwealthu", "answer": "Ano", "correct answer": ""},
{"text": "Brugge je město v Nizozemsku", "answer": "Ne", "correct answer": "Uvedené město se nachází v Belgii"},
{"text": "Jihoafrická republika uznává oficiálně 13 jazyků", "answer": "Ne", "correct answer": "Oficiálně uznává 11 jazyků"},
{"text": "Rozsáhlé teritorium Nunavut, které slouží jako samosprávné území Eskymákům, se nachází na Aljašce", "answer": "Ne", "correct answer": "Nachází se v Kanadě"},
{"text": "Katar je republika", "answer": "Ne", "correct answer": "Katar je ve skutečnosti monarchie"},
{"text": "Llanos je rozsáhlá oblast pamp na území Argentiny", "answer": "Ne", "correct answer": "Jde o rozsáhlé prérie, které se rozkládají na území Venezuely a Kolumbie"},
{"text": "Yorkshire je největší anglické hrabství", "answer": "Ano", "correct answer": ""},
{"text": "Republika Východní Timor se nachází v souostroví Velké Sundy", "answer": "Ne", "correct answer": "Nachází se v Malých Sundách"},
{"text": "Na ostrově Curaçao hraje turismus dominantní roli", "answer": "Ano", "correct answer": ""},
{"text": "Počet obyvatel ve Vietnamu je přibližně 99 milionů", "answer": "Ano", "correct answer": ""},
{"text": "Brazílie je 5. největší stát na světě", "answer": "Ano", "correct answer": ""},
{"text": "Honosná klasicistní budova 'památník Walhalla' se nachází v Německu", "answer": "Ano", "correct answer": ""},
{"text": "Mali je převážně křesťanská země", "answer": "Ne", "correct answer": "Mali je výhradně muslimský stát"},
{"text": "Newyorské metro je co do počtu stanic třetím největším systémem metra na světě", "answer": "Ne", "correct answer": "Metro v New Yorku je v tomto ukazateli na prvním místě na světě"},
{"text": "Nejvíce počasí v Číně ovlivňují monzuny", "answer": "Ano", "correct answer": ""},
{"text": "Na soustroví Galapágy se nachází spoustu endemických druhů živočichů včetně leguána mořského", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší hora Rakouska je Grossglockner", "answer": "Ano", "correct answer": ""},
{"text": "Drtivá většina obyvatel Tuniska je ortodoxního sunnitského islámského vyznání", "answer": "Ano", "correct answer": ""},
{"text": "Javier Hernández je velmi slavný mexický fotbalista", "answer": "Ano", "correct answer": ""},
{"text": "Ujgurové jsou turkické etnikum střední Asie", "answer": "Ano", "correct answer": ""},
{"text": "Vodopády Iguacu se nachází na hranicích Brazílie a Uruguaye", "answer": "Ne", "correct answer": "Jsou na pomezí Brazílie a Argentiny"},
{"text": "Portugalsko je kromě jiného známé produkcí korku", "answer": "Ano", "correct answer": ""},
{"text": "Nejpopulárnějším sportem v Angole je fotbal", "answer": "Ne", "correct answer": "Vzhledem ke zbytku Afriky se trochu překvapivě jedná o basketbal"},
{"text": "Měnou v Salvadoru je americký dolar", "answer": "Ano", "correct answer": ""},
{"text": "Bangladéš leží ve společné deltě řek Gangy a Indu", "answer": "Ne", "correct answer": "Leží v deltě řek Gangy a Brahmaputry"},
{"text": "Hlavní město Francouzské Guyany je Caen", "answer": "Ne", "correct answer": "Cayenne"},
{"text": "Nejvýznamnější řeky v Chorvatsku jsou Dunaj, Sáva a Dráva", "answer": "Ano", "correct answer": ""},
{"text": "Ve Rwandě se drtivá většina obyvatel hlásí k islámu", "answer": "Ne", "correct answer": "Většina obyvatel se hlásí ke křesťanství"},
{"text": "Film 'Faunův Labyrint' je film, který byl natočen v Mexiku", "answer": "Ano", "correct answer": ""},
{"text": "Bojové umění taekwondo vzniklo v Japonsku", "answer": "Ne", "correct answer": "Vzniklo v Jižní Koreji"},
{"text": "Nejvyšší hora v Jižní Americe je Huascarán", "answer": "Ne", "correct answer": "Aconcagua"},
{"text": "O souostroví Falklandy vede dlouhodobý spor Argentina s Velkou Británií", "answer": "Ano", "correct answer": ""},
{"text": "Dunaj je druhá nejdelší řeka u v Evropě", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší socha Ježíše Krista se nachází v Polsku", "answer": "Ano", "correct answer": ""},
{"text": "Vrchol Petrovy kameny, tvořený třemi mohutnými skalisky a v minulosti považovaný za dějiště čarodějnických sletů, se nachází v Moravskoslezských Beskydech", "answer": "Ne", "correct answer": "Nachází se v Hrubém Jeseníku"},
{"text": "Mercatorovo zobrazení je kartografické válcové zobrazení, kde se zvětšuje zkreslení směrem od rovníků k pólům a patří v současnosti k nejvíce používaným", "answer": "Ano", "correct answer": ""},
{"text": "Bolívie ztratila přístup k Tichému oceánu v tzv. válce o ledek v roce 1879", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Albánie je Tirana", "answer": "Ano", "correct answer": ""},
{"text": "Od roku 2021 je Estonsko jedinou zemí na světě, kde prezidentský i premiérský post zastává žena", "answer": "Ano", "correct answer": ""},
{"text": "Měnou ve Finsku je finská markka", "answer": "Ne", "correct answer": "Od roku 2002 se ve Finsku platí eurem"},
{"text": "Měnou ve Francii je francouzský frank", "answer": "Ne", "correct answer": "Od roku 2002 se ve Francii platí eurem"},
{"text": "Samba je zapsána na seznam světového nehmotného kulturního dědictví UNESCO", "answer": "Ano", "correct answer": ""},
{"text": "Státní zřízení Andorry je konstituční monarchie", "answer": "Ne", "correct answer": "polovolená parlamentní diarchie"},
{"text": "Sluneční terminátor je rozhraní mezi Sluncem osvětlenou a neosvětlenou částí planety nebo měsíce sluneční soustavy", "answer": "Ano", "correct answer": ""},
{"text": "Měnou v Chorvatsku je v současnosti euro", "answer": "Ano", "correct answer": ""},
{"text": "K nejpopulárnějším sportům v Irsku patří fotbal a rugby", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší hora v Ekvádoru je Cotopaxi", "answer": "Ne", "correct answer": "Chimborazo"},
{"text": "Přezdívka belgické fotbalové reprezentace je 'Rudí ďáblové", "answer": "Ano", "correct answer": ""},
{"text": "Geoid je fyzikální model povrchu Země při střední hladině světových oceánů, ale také myšleně prochází i pod povrchem Země", "answer": "Ano", "correct answer": ""},
{"text": "Na Islandu žije více obyvatel než v Lucembursku", "answer": "Ne", "correct answer": "V Lucembursku žije téměř 2x více obyvatel"},
{"text": "Hlavní město v Kazachstánu je Nur-sultan", "answer": "Ne", "correct answer": "Hlavní město je Astana. Mezi roky 2019 a 2022 byla Astana dočasně přejmenována na Nur-Sultan na počest prvního zesnulého prezidenta Kazachstánu, ale v roce 2023 byla opět přejmenována na Astanu."},
{"text": "Národní sport v Guyaně je fotbal", "answer": "Ne", "correct answer": "Kriket"},
{"text": "Bělorusko není, pokud jde o dovoz surovin a vývozní trh, závislé na Rusku", "answer": "Ne", "correct answer": "Je na Rusku velmi závislé"},
{"text": "Měna v Lichtenštejnsku je euro", "answer": "Ne", "correct answer": "Švýcarský frank"},
{"text": "Creek je označení pro občasný vodní tok v Austrálii, který je většinu roku bez vody a naplní se jen po rozsáhlejších dešťových srážkách", "answer": "Ano", "correct answer": ""},
{"text": "Měna v Litvě je lat", "answer": "Ne", "correct answer": "V současnosti se zde platí eurem"},
{"text": "Hlavní město Chile je Santiago de Chile", "answer": "Ano", "correct answer": ""},
{"text": "V Bosně a Hercegovině žije přibližně 3,5 milionu obyvatel", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Lotyšska je Vilnius", "answer": "Ne", "correct answer": "Riga"},
{"text": "Největší jezero v Itálii je Lago Maggiore", "answer": "Ne", "correct answer": "Největší je Lago di Garda (Gardské jezero)"},
{"text": "Ayutthaya je významné starobylé město, které se nachází v Thajsku", "answer": "Ano", "correct answer": ""},
{"text": "Zpěvačka Shakira pochází z Venezuely", "answer": "Ne", "correct answer": "Pochází z Kolumbie"},
{"text": "V Bulharsku je významná italská menšina", "answer": "Ne", "correct answer": "z významných menšin je tu romská a turecká"},
{"text": "Ochridský region, který patří do světového kulturního dědictví UNESCO a nachází se v něm stejnojmenné jezero se nachází v Černé Hoře", "answer": "Ne", "correct answer": "Nachází se v Severní Makedonii"},
{"text": "Mogota je vápencový pahorek s velmi strmými svahy v krasových oblastech vysoký do 300m. Nachází se typicky na Filipínách, Kubě nebo v Číně", "answer": "Ano", "correct answer": ""},
{"text": "Polje jsou rozsáhlé roviny, nacházející se v nížinatých oblastech, které byly vymodelované činností ledovců", "answer": "Ne", "correct answer": "Jsou to protáhlé, většinou uzavřené a rozlehlé krasové sníženiny, ohraničené příkrými svahy s ostrým úpatím"},
{"text": "Paraguay je jediným úředním jazykem Španělština", "answer": "Ne", "correct answer": "Ve skutečnosti je Paraguay bilinguální a druhým úředním jazykem je guaraní"},
{"text": "Bývalé královské hlavní město Cetinje leží v Srbsku", "answer": "Ne", "correct answer": "nachází se v Černé Hoře"},
{"text": "Nejvyšší horou Lucemburska je Kneiff, který se nachází v Ardenách a jeho nadmořská výška činí 560 m. n. m.", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší hora v Maďarsku je Nógrád", "answer": "Ne", "correct answer": "Nejvyšší hora je Kékes s nadmořskou výškou 1014 m. n. m. Nógrád je maďarská župa"},
{"text": "Poutní kostel svatého Jana Nepomuckého na Zelené Hoře v České republice spadá pod kulturní světové dědictví UNESCO", "answer": "Ano", "correct answer": ""},
{"text": "Peruánská ekonomika patří mezi nejrychleji rostoucí ekonomiky na světě", "answer": "Ano", "correct answer": ""},
{"text": "Architektem hradu Karlštejn byl Matyáš z Arrasu", "answer": "Ano", "correct answer": ""},
{"text": "Nejvýznamnější a nejdelší řeka v Moldavsku je Dněstr", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší hora v Německu je Acherkogel", "answer": "Ne", "correct answer": "Zugspitze (2962 m. n. m.)"},
{"text": "Meandr je zákrut řeky způsobený boční erozí. Středový úhel oblouku musí být větší než 180°", "answer": "Ano", "correct answer": ""},
{"text": "Surinam je nejmenším nezávislým státem jihoamerického kontinentu", "answer": "Ano", "correct answer": ""},
{"text": "Rýn protéká postupně šesti státy: Švýcarskem, Lichtenštejnskem, Rakouskem, Německem, Francií a Nizozemskem", "answer": "Ano", "correct answer": ""},
{"text": "Jizerskohorské bučiny se v roce 2021 staly první českou přírodní památkou zařazenou na seznam Světového dědictví UNESCO", "answer": "Ano", "correct answer": ""},
{"text": "Největší ledovec kontinentální Evropy je Jostedalsbreen v Norsku", "answer": "Ano", "correct answer": ""},
{"text": "Sedimentace v geografii a geologii je proces ukládání pevných látek na dolních tocích řek, v jezerech a oceánech.", "answer": "Ano", "correct answer": ""},
{"text": "Natalia Oreiro známá z jihoamerických telenovel pochází z Uruguaye", "answer": "Ano", "correct answer": ""},
{"text": "Měna na Maltě je euro", "answer": "Ano", "correct answer": ""},
{"text": "Měna v Polsku je euro", "answer": "Ne", "correct answer": "Zlotý"},
{"text": "Slunovrat je astronomický termín, který se stane jednou za rok", "answer": "Ne", "correct answer": "Slunovraty jsou za rok dva. Letní a zimní."},
{"text": "Středověké opevnění města Bellinzona najdeme ve Švýcarsku", "answer": "Ano", "correct answer": ""},
{"text": "Ostrov Bonaire patří Venezuele", "answer": "Ne", "correct answer": "Je součástí Nizozemska"},
{"text": "Město Bamberg s velkou historií se nachází v Rakousku", "answer": "Ne", "correct answer": "Nachází se v Německu"},
{"text": "Hlavní město Maroka je Marrakesh", "answer": "Ne", "correct answer": "Rabat"},
{"text": "Ekumena je souhrn území trvale neosídlených", "answer": "Ne", "correct answer": "Je to přesně naopak. Jedná se o osídlené oblasti"},
{"text": "Wrangelův ostrov patří Norsku", "answer": "Ne", "correct answer": "Je součástí Ruska"},
{"text": "Vasco da Gama byl známý španělský mořeplavec", "answer": "Ne", "correct answer": "Pocházel z Portugalska"},
{"text": "Tlaková výše je v meteorologii označována jako anticyklóna", "answer": "Ano", "correct answer": ""},
{"text": "Pilot formule 1 a trojnásobný mistr světa Niki Lauda byl Němec", "answer": "Ne", "correct answer": "Byl to Rakušan"},
{"text": "Zambo je označení pro obyvatele Latinské Ameriky a popisuje potomka bělocha a černocha", "answer": "Ne", "correct answer": "Zambo je potomek černocha a indiána"},
{"text": "Barack Obama je asi nejznámějších představitelem mulata", "answer": "Ano", "correct answer": ""},
{"text": "Rumunský biolog Lazar Edeleanu objevil amfetamin", "answer": "Ano", "correct answer": ""},
{"text": "Petrohrad se nachází v ústí řeky Něvy", "answer": "Ano", "correct answer": ""},
{"text": "Mount Nimba je národní park v Guineji a Pobřeží Slonoviny. Nachází se v něm více než 200 endemických druhů", "answer": "Ano", "correct answer": ""},
{"text": "Machu Picchu se nachází v Bolívii", "answer": "Ne", "correct answer": "Nachází se v Peru"},
{"text": "Nejvyšší hora v Řecku je Mytikas v pohoří Olymp (2917 m. n. m.)", "answer": "Ano", "correct answer": ""},
{"text": "Arumunština je slovanský jazyk, kterým se mluví na jihu Maďarska", "answer": "Ne", "correct answer": "Románský jazyk velmi blízký rumunštině. Mluví se jím v Severní Makedonii, Albánii a v Řecku"},
{"text": "Meteora jsou monastýry na vrcholcích slepencových skal v oblasti Thesálie v Řecku", "answer": "Ano", "correct answer": ""},
{"text": "Oblík jsou zaoblené vrcholy jednotlivých pahorků v krasových oblastech", "answer": "Ne", "correct answer": "Jedná se o ledovcem ohlazenou nebo rýhovanou skalnatou vyvýšeninu. Oblíky jsou základním tvarem plošně působící glaciální eroze"},
{"text": "Měna v Severní Makedonii je Makedonský denár", "answer": "Ano", "correct answer": ""},
{"text": "Národní park Everglades se nachází v Jižní Karolíně", "answer": "Ne", "correct answer": "Nachází se na Floridě"},
{"text": "Mohorovičičova plocha diskontinuity je vrstva, která geologicky definuje přechod zemského pláště do zemského jádra", "answer": "Ne", "correct answer": "Jedná se o vrstvu mezi zemskou kůrou a zemským pláštěm"},
{"text": "Hlavní město Slovinska je Maribor", "answer": "Ne", "correct answer": "Lublaň"},
{"text": "Měna ve Srbsku je srbská kuna", "answer": "Ne", "correct answer": "srbský dinár"},
{"text": "Ron je glaciální svahový pohyb, kdy ledovec cestou zachytává různé pevné částice a touto erozní činností prohlubuje údolí", "answer": "Ne", "correct answer": "Jedná se o fluviální svahový pohyb spočívající v nesoustředěném stékání vody po povrchu terénu. Dochází k němu při větším dešti nebo nasycení půdy vodou"},
{"text": "Historické město Grand Bassam se nachází v Ghaně", "answer": "Ne", "correct answer": "Nachází se v Pobřeží Slonoviny"},
{"text": "Proslulá Canterburská katedrála s vedoucím představitelem anglikánské církve se nachází v Anglii", "answer": "Ano", "correct answer": ""},
{"text": "Jako neoficiální hlavní město Baskicka je považováno Bilbao", "answer": "Ano", "correct answer": ""},
{"text": "Moréna je široký závěr horského údolí, které má půlkruhovitý tvar, strmé až svislé skalní stěny a ploché nebo vyhloubené dno", "answer": "Ne", "correct answer": "Je to kamenný val vzniklý ledovcovou činností. Morény jsou tvořeny převážně ze špatně vytříděného materiálu, který se skládá z velkých balvanů až po malé jílové části"},
{"text": "Mulhacén je nejvyšší hora Pyrenejí", "answer": "Ne", "correct answer": "Nejvyšší hora Pyrenejí je Pico de Aneto (3404 m. n. m.)"},
{"text": "Středověké město Toruň, rodiště Mikuláše Koperníka, se nachází na Ukrajině", "answer": "Ne", "correct answer": "Nachází se v sousedním Polsku"},
{"text": "Kontinentální zemská kůra je tenčí než oceánská a má dvě vrstvy", "answer": "Ne", "correct answer": "Má 3 vrstvy a je tlustší než oceánská kůra"},
{"text": "Jezero Vänern je největší jezero ve Švédsku", "answer": "Ano", "correct answer": ""},
{"text": "Birnbrot (hruškový chléb) je tradiční pečivo švýcarských Alp a alpského předhůří", "answer": "Ano", "correct answer": ""},
{"text": "Deklinace je souřadnice, která udává úhel mezi rovinou deklinační kružnice hvězdy a rovinou deklinační kružnice procházející jarním bodem(Je obdobou geografické délky)", "answer": "Ne", "correct answer": "Jedná se souřadnici, která udává úhlovou vzdálenost rovnoběžky, na níž leží nebeské tělesko, od světového rovníku(je tedy obdobou geografické šířky)"},
{"text": "Turecko má po americké armádě druhé největší vojsko v rámci NATO s odhadem cca. 500 000 nasaditelných vojáků", "answer": "Ano", "correct answer": ""},
{"text": "Gagauzové jsou národ turkického původu, usídlených převážně v Moldávii a částečně na Ukrajině a v Rusku", "answer": "Ano", "correct answer": ""},
{"text": "Džengiš Čokusu(7439 m. n. m.) je nejvyšší hora pohoří Ťan-Šan", "answer": "Ano", "correct answer": ""},
{"text": "Stalagmit je krasový jev, který vyrůstá ze stropu jeskyně, kde protékají vodní roztoky obohacené rozpuštěnými minerálními složkami", "answer": "Ne", "correct answer": "Tento krasový jev vyrůstá z podlahy jeskyně, na kterou dopadají vodní roztoky obohacené o rozpuštěné minerální složky"},
{"text": "Hlavní město Zimbabwe je Harare", "answer": "ano", "correct answer": ""},
{"text": "Přibližně 80 procent rozlohy Kyrgyzstánu leží v nadmořské výšce nad 1000 m. n. m.", "answer": "Ne", "correct answer": "Podíl je dokonce vyšší než 94 procent rozlohy"},
{"text": "Největší ostrov na světě je Grónsko", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Kalifornie je Sacramento", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyěěí hora v Polsku je vrchol Rysy", "answer": "Ano", "correct answer": ""},
{"text": "Největší jezero v Evropě je Ladožské", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Lybie je Chartúm", "answer": "Ne", "correct answer": "Tripolis je správně"},
{"text": "Slavný pravoslavný klášter Rilský monastýr najdeme v Bulharsku", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší hora Francouzského středohoří je Puy Mary", "answer": "Ne", "correct answer": "Nejvyšší je Puy de Sancy"},
{"text": "Hlavní město Francouzské Guyany je Cayenne", "answer": "Ano", "correct answer": ""},
{"text": "Nejvyšší hora ve Finsku je Vantaa", "answer": "Ne", "correct answer": "Haltiatunturi je správně"},
{"text": "Nejvyšší hora v Irsku je Carrauntoohil", "answer": "Ano", "correct answer": ""},
{"text": "Havířov je okresní město v Moravskoslezském kraji", "answer": "Ne", "correct answer": "Havířov sice leží v Moravskoslezském kraji, ale není okresním městem"},
{"text": "Nejvyšší hora Šumavy je Pancíř", "answer": "Ne", "correct answer": "Nejvyšší je Plechý, na Německé straně v Bavorském lese je to Grosser Arber"},
{"text": "Nejvyšší činná sopka v Evropě je Etna", "answer": "Ano", "correct answer": ""},
{"text": "Norsko je svou rozlohou větší než Velká Británie", "answer": "Ano", "correct answer": ""},
{"text": "Přezdívka 'Hanácké Benátky' náleží městu Litovel", "answer": "Ano", "correct answer": ""},
{"text": "Ukerewe je jiné označení pro jezero Tanganika", "answer": "Ne", "correct answer": "Je to označení pro Viktoriino jezero"},
{"text": "Hlavní město státu New York je Albany", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Wisconsinu je Madison", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Jižní Dakoty je Helena", "answer": "Ne", "correct answer": "Pierre je správně"},
{"text": "Hlavní město Černé Hory je Priština", "answer": "Ne", "correct answer": "Podgorica je správně"},
{"text": "Národní sport v Litvě je basketbal", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Eritreje je Asmera", "answer": "Ano", "correct answer": ""},
{"text": "Česká republika se dělí na 14 krajů", "answer": "Ano", "correct answer": ""},
{"text": "Měna v Chorvatsku kuna je pojmenována podle jednoho z chorvatských panovníků", "answer": "Ne", "correct answer": "je pojmenována podle šelem s jejichž kožešinou se dříve obchodovalo"},
{"text": "Nejvyšší hora Rychlebských hor je Černá Hora", "answer": "Ne", "correct answer": "Smrk je správně"},
{"text": "Bezocasé kočky pochází z ostrova Man", "answer": "Ano", "correct answer": ""},
{"text": "Ostrava je 3. největší město v České republice", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Jordánska je Ammán", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město ostrova Sv. Lucie je Castries", "answer": "Ano", "correct answer": ""},
{"text": "Město Novi Sad leží v Bosně a Hercegovině", "answer": "Ne", "correct answer": "Leží ve Srbsku"},
{"text": "Město Humenné se nachází ve Východním Slovensku", "answer": "Ano", "correct answer": ""},
{"text": "Známý přístav Terst se nachází ve Slovinsku", "answer": "Ne", "correct answer": "V současnosti leží v Itálii"},
{"text": "Konflikt o Náhorní Karabach mezi sebou měli Ázerbajdžán a Gruzie", "answer": "Ne", "correct answer": "Konflikt byl mezi Ázerbajdžáném a Arménií"},
{"text": "Fotbalista Cristiano Ronaldo pochází z Madeiry", "answer": "Ano", "correct answer": ""},
{"text": "Hlavní město Floridy je Tallahassee", "answer": "Ano", "correct answer": ""},
{"text": "Upír obecný žije v Africe", "answer": "Ne", "correct answer": "Žije ve Střední a Jižní Americe"},
{"text": "Hlavní město Mosambiku je Maputo", "answer": "Ano", "correct answer": ""},
]